# External gems
gems:
  # - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Diana Pacheco Coaching
subtitle: "¿Qué te falta para ser la persona que quieres ser?"
email: dianapachecoamaral@gmail.com
name: Diana Pacheco Amaral
description: > 
  "Blog personal de coaching, inteligencia emocional, neurocoaching y otras demás tonterías de la vida humana"
url: "https://dianapachecocoach.github.io/" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives: 
#   enabled: 
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'

# Disqus comments
disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:

  - cat: automotivación
    desc: "Automotivarse es darse a uno mismo las razones, impulso, entusiasmo e interés con el que provocar una acción específica o un determinado comportamiento."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: didipache
    url: https://twitter.com/didipache
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: diana.pachecoamaral
    url: https://www.facebook.com/diana.pachecoamaral
    desc: Friend me on Facebook
    share: true

  - name: LinkedIn
    icon: linkedin
    username: Diana Pacheco Amaral
    url: https://www.linkedin.com/in/diana-pacheco-amaral-4368b436/
    desc: Connect with me on LinkedIn
    share: true


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
